### ISSUE TITLE
Roles contract doesn't exist on mainnet

### ISSUE THREAD

**Issue by fleupold** [cowdao-grants/mb-billing#26]
This contract only exists on Sepolia.

https://github.com/cowdao-grants/mb-billing/blob/f997e6dafbe41b3f56559e405df6b6f0e2ec36b9/src/billingContract.ts#L36

@cowanator did you deploy this contract (ie. will it be different for every Safe) or is this a singleton contract that only exists once per chain and was deployed by the Zodiac team?

If the former, it should probably become an environment variable.

**Comment by cowanator** [comment]
Yes, this was deployed by me on Sepolia. The instructions to deploy are here:

https://github.com/cowdao-grants/mb-billing/blob/f997e6dafbe41b3f56559e405df6b6f0e2ec36b9/README.md?plain=1#L90-L105

We do need to make this an env var instead of hard-coding an address here though. Will update with a PR soon.
